{% set name = "argos" %}
{% set version = "0.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/argos-{{ version }}.tar.gz
  sha256: ae4aee31d7e9d74465874494a8354d12a04871e5388da8ece653423b42d2ecfc

build:
  number: 1
  noarch: python
  entry_points:
    - argos = argos.main:main
    - argos_make_wrappers = argos.argos_make_wrappers:main
    - argosw = argos.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cmlib >=1.1.0
    - numpy >=1.11
    - pgcolorbar >=1.1.0
    - pyqtgraph >=0.10
    - python >={{ python_min }}

test:
  imports:
    - argos
    - argos.collect
  commands:
    - pip check
    - argos --help
    - argos_make_wrappers --help
    - argosw --help
  requires:
    - pip
    - pyqt >=5.12
    - python {{ python_min }}

about:
  home: https://github.com/titusjan/argos
  summary: Argos HDF5/NetCDF/scientific data viewer.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - titusjan
